### ISSUE TITLE
Spiritdao

### ISSUE THREAD

**Issue by Warn95** [ava-labs/audits#1]
{"code":-32602,"message":"Esimate Gas Error","data":"Esimate Gas Error"}

A couple weeks ago the app froze and I got this error code and I cannot add or remove ghost, tomb when staked coins.

![Screenshot_20220116-105851_Coin98 Wallet](https://user-images.githubusercontent.com/91983236/149674020-94d8d0b0-9371-4ecc-bc4b-d1dcfe300d7c.jpg)

![Screenshot_20220116-105835_Coin98 Wallet](https://user-images.githubusercontent.com/91983236/149674027-404f808e-3fb3-427b-910b-108eff45aacd.jpg)

I've looked to see if it was something on my end and I havent sound a solution or info that might suggest that I lost my money due to ignorance or over sight on my part.
please help if possible.

**Comment by StephenButtolph** [comment]
This issue seems to be stale and not related to any of the contents of this repo. Going to close.
